

------------------------------------ GLOBAL ELECTRONICS RETAILER (MAVEN ANALYTICS PROJECT)

CREATE DATABASE GLOBAL_ELECTRONICS_RETAILER

USE GLOBAL_ELECTRONICS_RETAILER



-- IMPORTING SALES-COPY

SELECT * FROM SALES

-- DELIVERY DATE HAS INCONSISTENT DATE FORMAT AND MISSING VALUES

/*---- FOR INCONSISTENT FORMAT

	SELECT * FROM SALES
	
	-- MISSING VALUES PERCENTAGE
	SELECT SUM(CASE WHEN DELIVERY_DATE = ' ' THEN 1 ELSE 0 END) AS 'BLANKS', COUNT(*) AS 'TOT',  
			SUM(CASE WHEN DELIVERY_DATE = ' ' THEN 1 ELSE 0 END)*100.00/COUNT(*) AS 'PERCENTAGE'
	FROM SALES

	-- INCONSISTENCIES
	SELECT DELIVERY_DATE, TRY_CONVERT(DATE, DELIVERY_DATE, 101) AS 'NEW_DATE'
	FROM SALES
	WHERE DELIVERY_DATE != ' '

	UPDATE SALES SET DELIVERY_DATE = TRY_CONVERT(DATE, DELIVERY_DATE, 101)

	ALTER TABLE SALES
	ALTER COLUMN DELIVERY_DATE DATE

	SELECT COUNT(DELIVERY_DATE)
	FROM SALES
	WHERE DELIVERY_DATE = ' '

	-- REPLACING '1900-01-01' WITH NULL

	UPDATE SALES SET DELIVERY_DATE = NULL
	WHERE DELIVERY_DATE = '1900-01-01'

	---------------- INCONSISTENCIES SOLVED*/



-------- IMPORTING SALES_COPY FOR DATE ERROR (ORDER_DATE: YYYY-MM-DD , MM/DD/YYYY ---- DELIVERY_DATE: DD-MM-YYYY , MM/DD/YYYY)

	SELECT * FROM SALES_COPY

	SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SALES_COPY'

	-- MM/DD/YYYY -> YYYY-MM-DD (DEFAULT TRY_CONVERT)
	-- MM-DD-YYYY -> YYYY-MM-DD (DEFAULT TRY_CONVERT)

	SELECT ORDER_DATE, 
			MONTH(ORDER_DATE) AS 'MONTH', 
			TRY_CONVERT(DATE, ORDER_DATE) AS 'CON_OD', 
			MONTH(TRY_CONVERT(DATE, ORDER_DATE)) AS 'CONV_MONTH'
	FROM SALES COPY


	-- CONVERTING ORDER_DATE TO DATE BY USING TRY_CONVERT
	UPDATE SALES_COPY SET ORDER_DATE = TRY_CONVERT(DATE, ORDER_DATE)

	ALTER TABLE SALES_COPY
	ALTER COLUMN ORDER_DATE DATE

	-- CONVERTING DELIVERY_DATE TO DATE BY USING TRY_CONVERT
	UPDATE SALES_COPY SET DELIVERY_DATE = TRY_CONVERT(DATE, DELIVERY_DATE)

	ALTER TABLE SALES_COPY
	ALTER COLUMN DELIVERY_DATE DATE

	UPDATE SALES_COPY SET DELIVERY_DATE = NULL WHERE DELIVERY_DATE = '1900-01-01'

	SELECT DELIVERY_DATE FROM SALES_COPY

	-- CHECKING % OF MISSING VALUES (HAS TO BE 79%)
	SELECT SUM(CASE WHEN DELIVERY_DATE IS NULL THEN 1 ELSE 0 END) AS 'BLANKS', COUNT(*) AS 'TOT',  
			SUM(CASE WHEN DELIVERY_DATE IS NULL THEN 1 ELSE 0 END)*100.00/COUNT(*) AS 'PERCENTAGE'
	FROM SALES_COPY


------------------------------------------------------------------ NOW THE SALES_COPY TABLE IS SALES TABLE


--  IMPORTING CUSTOMERS TABLE

	SELECT * FROM CUSTOMERS

	WITH CTE1 AS
	(SELECT BIRTHDAY, TRY_CONVERT(DATE, BIRTHDAY, 101) AS 'NEW'
	FROM CUSTOMERS)

	SELECT BIRTHDAY FROM CTE1 
	WHERE NEW = ' '

	UPDATE CUSTOMERS SET BIRTHDAY = TRY_CONVERT(DATE, BIRTHDAY, 101)
	
	ALTER TABLE CUSTOMERS
	ALTER COLUMN BIRTHDAY DATE

	SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CUSTOMERS'



-- IMPORTING EXCHANGE_RATES TABLE

	SELECT * FROM EXCHANGE_RATES

	SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EXCHANGE_RATES'

	SELECT [DATE], MONTH(DATE) AS 'MONTH', TRY_CONVERT(DATE, DATE) AS 'YYYY-MM-DD-'
	FROM EXCHANGE_RATES
	WHERE DATE LIKE '%-%'

	SELECT [DATE], MONTH(DATE) AS 'MONTH', TRY_CONVERT(DATE, DATE) AS 'YYYY-MM-DD/'
	FROM EXCHANGE_RATES
	WHERE DATE LIKE '%/%'

	UPDATE EXCHANGE_RATES SET [DATE] = TRY_CONVERT(DATE, [DATE])

	ALTER TABLE EXCHANGE_RATES ALTER COLUMN [DATE] DATE

	SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EXCHANGE_RATES'



-- IMPORTING PRODUCTS TABLE

	SELECT * FROM PRODUCTS
	
	SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PRODUCTS'



-- IMPORTING STORES TABLE

	SELECT * FROM STORES

	SELECT OPEN_DATE, TRY_CONVERT(DATE, OPEN_DATE, 101) AS 'NEW'
	FROM STORES

	UPDATE STORES SET OPEN_DATE = TRY_CONVERT(DATE, OPEN_DATE, 101)

	ALTER TABLE STORES ALTER COLUMN OPEN_DATE DATE

	SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'STORES'





------------------------------ DATA MODELING

SELECT * FROM INFORMATION_SCHEMA.TABLES 

SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SALES'

SELECT * FROM SALES
SELECT * FROM CUSTOMERS
SELECT * FROM STORES
SELECT * FROM PRODUCTS
SELECT * FROM EXCHANGE_RATES


------------ PRIMARY KEYS
	--1. SALES 
	ALTER TABLE SALES 
	ALTER COLUMN ORDER_NUMBER INT NOT NULL

	ALTER TABLE SALES 
	ALTER COLUMN LINE_ITEM INT NOT NULL

	ALTER TABLE SALES 
	ADD CONSTRAINT PK1 PRIMARY KEY(ORDER_NUMBER, LINE_ITEM)

	-- FOUND DUPLICATE KEY IN ORDER_NUMBER COLUMN (ORDER_NUMBER AND LINE_ITEM TOGETHER BEHAVE AS UNIQUE IDENTIFIER FOR EACH ROW)

	SELECT ORDER_NUMBER, LINE_ITEM, COUNT(*)
	FROM SALES 
	GROUP BY ORDER_NUMBER, LINE_ITEM
	HAVING COUNT(*) >1

	--2. CUSTOMERS

	SELECT * FROM CUSTOMERS

	SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CUSTOMERS'

	SELECT CUSTOMER_KEY, COUNT(*)
	FROM CUSTOMERS
	GROUP BY CUSTOMER_KEY
	HAVING COUNT(*)>1

	ALTER TABLE CUSTOMERS
	ALTER COLUMN CUSTOMER_KEY INT NOT NULL

	ALTER TABLE CUSTOMERS
	ADD CONSTRAINT PK2 PRIMARY KEY (CUSTOMER_KEY)

-- 3. EXCHANGE_RATES

	SELECT * FROM INFORMATION_SCHEMA.TABLES 

	SELECT * FROM EXCHANGE_RATES

	-- PRIMARY KEY IN EXCHNAGE_RATES (DATE, CURRENCY)

	ALTER TABLE EXCHANGE_RATES
	ALTER COLUMN [DATE] DATE NOT NULL

	ALTER TABLE EXCHANGE_RATES
	ALTER COLUMN CURRENCY VARCHAR(50)  NOT NULL

	ALTER TABLE EXCHANGE_RATES
	ADD CONSTRAINT PK_1 PRIMARY KEY ([DATE], CURRENCY)


-- 4. PRODUCTS

	SELECT * FROM PRODUCTS
	
	SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PRODUCTS'

SELECT * FROM SALES
SELECT * FROM CUSTOMERS
SELECT * FROM STORES
SELECT * FROM PRODUCTS
SELECT * FROM EXCHANGE_RATES

	ALTER TABLE PRODUCTS
	ALTER COLUMN PRODUCT_KEY INT NOT NULL

	ALTER TABLE PRODUCTS
	ADD CONSTRAINT PK3 PRIMARY KEY (PRODUCT_KEY)


-- 5. STORES

	SELECT * FROM STORES

	ALTER TABLE STORES
	ALTER COLUMN STORE_KEY INT NOT NULL
	
	ALTER TABLE STORES
	ADD CONSTRAINT PK4 PRIMARY KEY (STORE_KEY)


------------ FOREIGN KEYS

SELECT * FROM SALES
SELECT * FROM CUSTOMERS
SELECT * FROM STORES
SELECT * FROM PRODUCTS
SELECT * FROM EXCHANGE_RATES

--1. SALES TABLE 

	-- CUSTOMER_KEY
	SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SALES'
	SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CUSTOMERS'

	ALTER TABLE SALES 
	ALTER COLUMN CUSTOMER_KEY INT

	ALTER TABLE SALES 
	ADD CONSTRAINT FK1 FOREIGN KEY (CUSTOMER_KEY) REFERENCES CUSTOMERS (CUSTOMER_KEY)

	-- STORE_KEY
	SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SALES'
	SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'STORES'

	ALTER TABLE SALES 
	ALTER COLUMN STORE_KEY INT

	ALTER TABLE SALES 
	ADD CONSTRAINT FK2 FOREIGN KEY (STORE_KEY) REFERENCES STORES (STORE_KEY)

	-- PRODUCT_KEY
	SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SALES'
	SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PRODUCTS'

	ALTER TABLE SALES
	ALTER COLUMN PRODUCT_KEY INT

	ALTER TABLE SALES
	ADD CONSTRAINT FK3 FOREIGN KEY (PRODUCT_KEY) REFERENCES PRODUCTS (PRODUCT_KEY)


	SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SALES'


	SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES 

-- 2. CUSTOMERS

	SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CUSTOMERS'

-- 3. EXCHANGE_RATES
	
	SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EXCHANGE_RATES'

	-- FOREIGN KEY (ORDER_DATE, CURRENCY_CODE)

	ALTER TABLE SALES 
	ADD CONSTRAINT FK_1 FOREIGN KEY (ORDER_DATE, CURRENCY_CODE) REFERENCES EXCHANGE_RATES ([DATE], CURRENCY)

-- 4. PRODUCTS, STORES
	
	SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PRODUCTS'
	SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'STORES'





	

