


------------------------------------ SQL ANALYSIS

--1. WHAT TYPES OF PRODUCTS DOES THE COMPANY SELL AND WHERE ARE THE CUSTOMERS LOCATED?
	SELECT CATEGORY
	FROM PRODUCTS
	GROUP BY CATEGORY

	SELECT COUNT(DISTINCT PRODUCT_KEY) AS 'PRODUCTS' FROM PRODUCTS

	SELECT * FROM CUSTOMERS
	SELECT * FROM SALES

	SELECT CONCAT(COUNTRY,' ', STATE_CODE , ' ', CITY, ' ', ZIP_CODE)  AS CUSTOMER_LOCATION
	FROM CUSTOMERS
	GROUP BY CONCAT(COUNTRY,' ', STATE_CODE, ' ', CITY, ' ',ZIP_CODE) 
	ORDER BY CONCAT(COUNTRY,' ', STATE_CODE, ' ', CITY, ' ',ZIP_CODE) 

	SELECT DISTINCT COUNTRY
	FROM CUSTOMERS

	-- COUNTRY WISE CUSTOMERS
	SELECT COUNTRY, COUNT(DISTINCT CUSTOMER_KEY) AS 'NO_OF_CUSTOMERS' 
	FROM CUSTOMERS C
	GROUP BY COUNTRY
	ORDER BY NO_OF_CUSTOMERS DESC

	-- COUNTRY WISE ORDERS
	SELECT COUNTRY, COUNT(DISTINCT ORDER_NUMBER) AS 'NO_OF_ORDERS' 
	FROM CUSTOMERS C
	JOIN SALES S
	ON C.CUSTOMER_KEY = S.CUSTOMER_KEY
	GROUP BY COUNTRY
	ORDER BY NO_OF_ORDERS DESC




	-- BEST PERFORMING COUNTRIES (COUNTRY WISE SALES)

	WITH CTE1 AS 
	(SELECT ORDER_NUMBER, CUSTOMER_KEY, LINE_ITEM, ORDER_DATE, S.PRODUCT_KEY, CURRENCY_CODE,
	 QUANTITY, EXCHANGE, UNIT_PRICE_USD, EXCHANGE*UNIT_PRICE_USD AS CONV_PRICE
	FROM EXCHANGE_RATES ER
	JOIN SALES S
	ON S.ORDER_DATE = ER.DATE AND S.CURRENCY_CODE = ER. CURRENCY
	JOIN PRODUCTS P 
	ON S.PRODUCT_KEY = P.PRODUCT_KEY)

	SELECT COUNTRY, ROUND(SUM(CONV_PRICE*QUANTITY/1000000),2) AS TOTAL_SALES_MILLIONS
	FROM CTE1 
	JOIN CUSTOMERS C
	ON CTE1.CUSTOMER_KEY = C.CUSTOMER_KEY
	GROUP BY COUNTRY
	ORDER BY ROUND(SUM(CONV_PRICE*QUANTITY/1000000),2) DESC


--2. ARE THERE ANY SEASONAL PATTERNS OR TRENDS FOR ORDER VOLUME OR REVENUE?
	
	SELECT * FROM SALES
	SELECT * FROM PRODUCTS
	
	-- VOLUME TREND
	WITH CTE1 AS 
	(SELECT YEAR(ORDER_DATE) AS 'ORDER_YEAR', 
		COUNT(DISTINCT ORDER_NUMBER) AS 'VOLUME',
		LAG(COUNT(*)) OVER (ORDER BY YEAR(ORDER_DATE)) AS 'PREVIOUS'
	FROM SALES
	GROUP BY YEAR(ORDER_DATE))

	SELECT ORDER_YEAR, VOLUME, COALESCE(ROUND((VOLUME-PREVIOUS)*100.0/PREVIOUS,2),0) AS '%_CHANGE_VOLUME'
	FROM CTE1
	ORDER BY ORDER_YEAR;


------ SALES TREND
	WITH CTE AS
	(SELECT ORDER_DATE, ORDER_NUMBER, LINE_ITEM, CURRENCY_CODE, PRODUCT_KEY, QUANTITY, EXCHANGE
	FROM SALES S
	JOIN EXCHANGE_RATES ER
	ON S.ORDER_DATE = ER.[DATE] AND S.CURRENCY_CODE = ER.CURRENCY),

	CTE2 AS 
	(SELECT ORDER_DATE, ORDER_NUMBER, LINE_ITEM, CTE.PRODUCT_KEY, YEAR(ORDER_DATE) AS 'ORDER_YEAR', MONTH(ORDER_DATE) AS 'ORDER_MONTH', 
		QUANTITY, EXCHANGE*UNIT_PRICE_USD AS 'UNIT_PRICE'
	FROM CTE 
	JOIN PRODUCTS P
	ON CTE.PRODUCT_KEY = P.PRODUCT_KEY
	GROUP BY ORDER_DATE, ORDER_NUMBER, LINE_ITEM, CTE.PRODUCT_KEY, ORDER_DATE, EXCHANGE, QUANTITY, UNIT_PRICE_USD)

	SELECT ORDER_YEAR, ROUND(SUM(QUANTITY*UNIT_PRICE)/1000000,2) AS 'REVENUE_MILLIONS'
	FROM CTE2
	GROUP BY ORDER_YEAR
	ORDER BY ORDER_YEAR




--3. HOW LONG IS THE AVERAGE DELIVERY TIME IN DAYS? HAS THAT CHANGED OVER TIME?
	WITH CTE1 AS 
	(SELECT ORDER_NUMBER, LINE_ITEM , ORDER_DATE, 
			MONTH(ORDER_DATE) AS 'O_MONTH', 
			DELIVERY_DATE, 
			MONTH(DELIVERY_DATE) AS 'D_MONTH', 
			YEAR(DELIVERY_DATE) AS 'D_YEAR',
			DATEDIFF(DAY, ORDER_DATE, DELIVERY_DATE) AS 'DAYS'
	FROM SALES
	WHERE DELIVERY_DATE IS NOT NULL
	GROUP BY ORDER_NUMBER, LINE_ITEM , ORDER_DATE, DELIVERY_DATE),

	CTE2 AS
	(SELECT D_YEAR, ROUND(AVG([DAYS]*1.0), 2) AS 'AVG_DELIVERY_DAYS',
		LAG(AVG([DAYS])) OVER (ORDER BY D_YEAR) AS 'PREVIOUS'
	FROM CTE1
	GROUP BY D_YEAR)

	SELECT D_YEAR, AVG_DELIVERY_DAYS, 
		COALESCE((AVG_DELIVERY_DAYS-PREVIOUS),0) AS 'CHANGE_IN_DAYS'
	FROM CTE2


--4. IS THERE A DIFFERENCE IN AVERAGE ORDER VALUE (AOV) FOR ONLINE VS. IN-STORE SALES?

	SELECT * FROM SALES
	SELECT * FROM CUSTOMERS
	SELECT * FROM STORES
	SELECT * FROM PRODUCTS
	SELECT * FROM EXCHANGE_RATES


	-- OFFLINE (DELIVERY_DATE IS NULL OR STORE_KEY != 0)

	SELECT * FROM SALES
	WHERE STORE_KEY != 0 


	WITH CTE AS
	(SELECT ORDER_DATE, ORDER_NUMBER, LINE_ITEM, CURRENCY_CODE, PRODUCT_KEY, STORE_KEY, QUANTITY, EXCHANGE
	FROM SALES S
	JOIN EXCHANGE_RATES ER
	ON S.ORDER_DATE = ER.[DATE] AND S.CURRENCY_CODE = ER.CURRENCY
	WHERE STORE_KEY != 0),

	CTE2 AS
	(SELECT ORDER_NUMBER, LINE_ITEM, QUANTITY, EXCHANGE*UNIT_PRICE_USD AS 'UNIT_PRICE'
	FROM CTE 
	JOIN PRODUCTS P
	ON CTE.PRODUCT_KEY = P.PRODUCT_KEY
	GROUP BY ORDER_NUMBER, LINE_ITEM, QUANTITY, EXCHANGE, UNIT_PRICE_USD),

	CTE3 AS
	(SELECT ORDER_NUMBER, SUM(QUANTITY*UNIT_PRICE) AS 'ORDER_VALUE'
	FROM CTE2
	GROUP BY ORDER_NUMBER)

	SELECT ROUND(SUM(ORDER_VALUE)/COUNT(ORDER_NUMBER),3) AS 'AOV_IN_STORE'
	FROM CTE3;

	-- ONLINE

	WITH CTE AS
	(SELECT ORDER_DATE, ORDER_NUMBER, LINE_ITEM, CURRENCY_CODE, PRODUCT_KEY, QUANTITY, EXCHANGE
	FROM SALES S
	JOIN EXCHANGE_RATES ER
	ON S.ORDER_DATE = ER.[DATE] AND S.CURRENCY_CODE = ER.CURRENCY
	WHERE STORE_KEY = 0),

	CTE2 AS
	(SELECT ORDER_NUMBER, LINE_ITEM, QUANTITY, EXCHANGE*UNIT_PRICE_USD AS 'UNIT_PRICE'
	FROM CTE 
	JOIN PRODUCTS P
	ON CTE.PRODUCT_KEY = P.PRODUCT_KEY
	GROUP BY ORDER_NUMBER, LINE_ITEM, QUANTITY, EXCHANGE, UNIT_PRICE_USD),

	CTE3 AS
	(SELECT ORDER_NUMBER, SUM(QUANTITY*UNIT_PRICE) AS 'ORDER_VALUE'
	FROM CTE2
	GROUP BY ORDER_NUMBER)

	SELECT ROUND(AVG(ORDER_VALUE),2) AS 'AOV_ONLINE'
	FROM CTE3;


	SELECT 2116.943 AS 'IN_STORE_AOV', 2048.63 AS 'ONLINE_AOV', 2116.943-2048.63 AS 'AOV_DIFFERENCE'








------------	AVERAGE_EXCHANGE_RATE FOR USA

SELECT CURRENCY_CODE, AVG(ER.Exchange) AS 'AVG_ER'
FROM SALES S
JOIN EXCHANGE_RATES AS ER
ON S.Order_Date = ER.DATE AND S.Currency_Code = ER.Currency
GROUP BY CURRENCY_CODE



SELECT * FROM EXCHANGE_RATES